Taylor done
ArtemGrom/PY111-task pull request #7
Opened 2021-06-02 11:09 UTC by ArtemGrom

2021-06-07 18:56 UTC, EnotYoyo requested changes
Реализация алгоритмов должна быть эффективной. 

Вычислять math.factorial(99), когда на предыдущем шаге получено значение факториала для 98 крайне неэффективно. Аналогично с числителем: если полученно x^98, то x^99 посчитать можно просто домножив на x, а не вычислять полную степень.

2021-06-20 21:28 UTC, ArtemGrom commented
change e^x and sin_x @EnotYoyo

2021-06-22 10:04 UTC, EnotYoyo requested changes

2021-06-22 10:04 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        b = factorial_iterative(2 * (i + 1) - 1)
А тут почему осталась эта функция? Она вообще не нужна для решения этого задания, ее нужно удалить.

2021-06-22 13:53 UTC, ArtemGrom commented on Tasks/b2_Taylor.py
> +        b = factorial_iterative(2 * (i + 1) - 1)
Какая функция?

2021-06-22 13:53 UTC, ArtemGrom commented on Tasks/b2_Taylor.py
> +        b = factorial_iterative(2 * (i + 1) - 1)
Какая функция? factorial_iterative - вычисляет факторил для синуса

2021-06-22 14:12 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        b = factorial_iterative(2 * (i + 1) - 1)
Смотрите, конкретно это задание сделано не для того, чтобы просто его запрограммировать. Это легко. Оно здесь, чтобы Вы увидели наиболее оптимальный способ решения казалось бы тривиальной задачи. 

Идея здесь в том, что каждый последующий элемент можно вычислять, используя результаты вычисления предыдущего. Таким образом, функция factorial_iterative не нужна, поскольку она значительно увеличивает сложность вычисления. 

Аналогично с вычислением степени, вычислить x ** n -  это непросто. Существуют [специальные алгортмы](https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%8B_%D0%B1%D1%8B%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%BE_%D0%B2%D0%BE%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F_%D0%B2_%D1%81%D1%82%D0%B5%D0%BF%D0%B5%D0%BD%D1%8C) для этого, которые используются в криптографических библиотеках. А у Вас оно возводится постепенно, следовательно возведение в степень можно просто заменить умножением.

2021-06-22 18:51 UTC, ArtemGrom commented on Tasks/b2_Taylor.py
> +        b = factorial_iterative(2 * (i + 1) - 1)
Я понял мысль, но опять не получается.
        a *= (x * x)
        b *= (i + 1) * (i + 2)
Я правильно делаю замену или мне еще надо над ними подумать?

2021-06-23 14:46 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        b = b * (i + 1) * (i + 2)
Ошибка в вычислении факториала. Range идет последовательно, т.е. i вначале равен 2, потом 3 и т.д. 

При таких i факториал считается неправильно

2021-06-24 09:56 UTC, ArtemGrom commented on Tasks/b2_Taylor.py
> +        b = b * (i + 1) * (i + 2)
Верно. это я уже торопился... нужно делать b = b * (i + 2) * (i + 3), но тест все равно не проходит. Мне теперь надо сравнивать с точностью 0.001?

2021-06-25 19:17 UTC, EnotYoyo approved these changes
Принято. Но функцию factorial_iterative можно было удалить в итоге :)

2021-06-26 05:40 UTC, merged